[theme]
base = "dark"
primaryColor = "#0051ba" # Kansas Blue for the primary process buttons
backgroundColor = "#333333" # TEXT Gray for the main dark grey background
secondaryBackgroundColor = "#333333" # TEXT Gray for input backgrounds to match[cite: 1]
textColor = "#ffffff" # White text for readability against the dark grey
font = "sans serif"
